export type UserRole = 'owner' | 'manager' | 'cashier' | 'stock_manager' | 'admin';

export type NavigationTab = 
  | 'pos' 
  | 'products' 
  | 'stock' 
  | 'customers' 
  | 'expenses' 
  | 'cash_register' 
  | 'proformas' 
  | 'invoices'
  | 'expiry' 
  | 'labels' 
  | 'dashboard' 
  | 'settings' 
  | 'admin';

export type PaymentMethod = 'cash' | 'orange_money' | 'moov_money' | 'wave_coris' | 'credit' | 'split';

export type StockMovementType = 'in_purchase' | 'out_manual' | 'sale' | 'return_customer' | 'damaged_loss' | 'inventory_adjustment';

export type ExpenseCategory = 
  | 'transport'
  | 'rent'
  | 'salaries'
  | 'electricity_sonabel'
  | 'water_onea'
  | 'communication'
  | 'goods_purchase'
  | 'repairs'
  | 'taxes'
  | 'other';

export interface UserPermissions {
  canAccessPos?: boolean;
  canAccessStock?: boolean;
  canAccessCustomers?: boolean;
  canAccessExpenses?: boolean;
  canAccessReports?: boolean;
  canGiveDiscount?: boolean;
  canManageUsers?: boolean;
}

export interface Business {
  id: string;
  name: string;
  accessCode: string; // Unique enterprise access code generated by Administrator (e.g. MAELYS)
  ownerId: string;
  ownerName?: string;
  phone: string;
  city: string;
  sector: string;
  ifu?: string;
  currency: string; // e.g. "FCFA"
  receiptFooter?: string;
  address?: string;
  status: 'active' | 'suspended';
  cloudSyncEnabled?: boolean;
  isDemo?: boolean;
  createdAt: string;
}

export interface AppUser {
  id: string;
  businessId: string;
  name: string;
  phone: string;
  role: UserRole;
  pin?: string; // 4-digit POS / manager PIN
  active: boolean;
  permissions?: UserPermissions;
  createdAt: string;
}

export interface Product {
  id: string;
  businessId: string;
  name: string;
  sku: string;
  barcode?: string;
  category: string;
  unit: string; // e.g. "Pièce", "Carton", "Paquet", "Flacon", "Lot", "Paire", "Kg"
  purchasePrice: number;
  salePrice: number;
  wholesalePrice?: number; // Gros
  semiWholesalePrice?: number; // Demi-Gros
  discountPrice?: number;
  currentStock: number;
  alertThreshold: number;
  expiryDate?: string; // YYYY-MM-DD
  batchNumber?: string;
  imageUrl?: string;
  supplier?: string;
  archived: boolean;
  createdAt: string;
}

export interface CartItem {
  product: Product;
  quantity: number;
  unitPrice: number;
  discount: number; // in FCFA or calculated
  priceType?: 'retail' | 'wholesale' | 'semi-wholesale';
}

export interface SaleItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  purchasePrice: number;
  subtotal: number;
  totalCost: number;
}

export interface Sale {
  id: string;
  businessId: string;
  receiptNumber: string;
  sellerId: string;
  sellerName: string;
  customerId?: string;
  customerName?: string;
  items: SaleItem[];
  subtotal: number;
  discount: number;
  total: number;
  totalCost: number;
  profit: number;
  paymentMethod: PaymentMethod;
  paymentBreakdown?: {
    cash?: number;
    orangeMoney?: number;
    moovMoney?: number;
    waveCoris?: number;
    credit?: number;
  };
  loyaltyPointsUsed?: number;
  loyaltyDiscount?: number;
  loyaltyPointsEarned?: number;
  quotationId?: string;
  notes?: string;
  createdAt: string;
}

export interface StockMovement {
  id: string;
  businessId: string;
  productId: string;
  productName: string;
  type: StockMovementType;
  quantity: number;
  previousStock: number;
  newStock: number;
  reason: string;
  userId: string;
  userName: string;
  createdAt: string;
}

export interface Customer {
  id: string;
  businessId: string;
  name: string;
  phone: string;
  address?: string;
  totalDebt: number;
  dueDate?: string; // YYYY-MM-DD
  loyaltyPoints?: number;
  loyaltyTier?: 'Bronze' | 'Silver' | 'Gold' | 'VIP';
  totalSpent?: number;
  notes?: string;
  createdAt: string;
}

export interface CustomerPayment {
  id: string;
  businessId: string;
  customerId: string;
  customerName: string;
  amount: number;
  paymentMethod: PaymentMethod;
  recordedBy: string;
  recordedByName: string;
  notes?: string;
  createdAt: string;
}

export interface Expense {
  id: string;
  businessId: string;
  category: ExpenseCategory;
  customCategory?: string;
  amount: number;
  paymentMethod: PaymentMethod;
  beneficiary: string;
  recordedBy: string;
  recordedByName: string;
  notes?: string;
  createdAt: string;
}

export interface CashSession {
  id: string;
  businessId: string;
  userId: string;
  userName: string;
  openedAt: string;
  closedAt?: string;
  initialFloat: number; // Fond de caisse initial
  totalCashSales: number;
  totalOrangeMoneySales: number;
  totalMoovMoneySales: number;
  totalWaveSales: number;
  totalCreditSales: number;
  totalCashIn: number; // Entrées manuelles
  totalCashOut: number; // Sorties manuelles
  expectedCashInDrawer: number;
  actualCashCounted?: number;
  discrepancy?: number;
  status: 'open' | 'closed';
  closingNotes?: string;
  createdAt: string;
}

export interface QuotationItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  subtotal: number;
}

export interface Quotation {
  id: string;
  businessId: string;
  quotationNumber: string;
  customerId?: string;
  customerName: string;
  customerPhone?: string;
  items: QuotationItem[];
  subtotal: number;
  discount: number;
  taxRate?: number;
  taxAmount?: number;
  total: number;
  validUntil: string;
  status: 'draft' | 'sent' | 'converted' | 'cancelled';
  convertedSaleId?: string;
  notes?: string;
  createdBy: string;
  createdByName: string;
  createdAt: string;
}

export interface InvoiceItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  subtotal: number;
}

export interface Invoice {
  id: string;
  businessId: string;
  invoiceNumber: string;
  customerId?: string;
  customerName: string;
  customerPhone?: string;
  items: InvoiceItem[];
  subtotal: number;
  discount: number;
  taxRate?: number;
  taxAmount?: number;
  total: number;
  amountPaid: number;
  status: 'unpaid' | 'partial' | 'paid' | 'cancelled';
  dueDate?: string;
  linkedSaleId?: string;
  notes?: string;
  createdBy: string;
  createdByName: string;
  createdAt: string;
}

export interface NotificationItem {
  id: string;
  title: string;
  message: string;
  type: 'warning' | 'info' | 'success' | 'danger';
  timestamp: string;
  read: boolean;
  linkTab?: NavigationTab;
}

export interface BusinessSummary {
  todaySales: number;
  todaySalesCount: number;
  todayProfit: number;
  todayExpenses: number;
  weekSales: number;
  monthSales: number;
  monthProfit: number;
  monthExpenses: number;
  totalPendingDebts: number;
  lowStockCount: number;
  outOfStockCount: number;
  expiringProductsCount?: number;
  activeCashSession?: CashSession | null;
}

export interface QueuedMutation {
  id: string;
  collection: string;
  docId: string;
  action: 'set' | 'update' | 'delete';
  payload?: any;
  timestamp: string;
  description: string;
  retryCount?: number;
}
